### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by Jeremy-Laier** [playcommunity/play-mongo#2]
Having problems actually connecting to the DB. 

Module code:
```scala
  Mongo.setModelsPackage("models")
  lazy val mongo: Mongo = Mongo(MongoConfig(
    "name", "testdb", "uri"))
```

Stack trace error:

```
play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: No SSL support in java.nio.channels.AsynchronousSocketChannel. For SSL support use com.mongodb.connection.netty.NettyStreamFactoryFactory]
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:211)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:142)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:300)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:190)
        at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1289)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
Caused by: java.lang.UnsupportedOperationException: No SSL support in java.nio.channels.AsynchronousSocketChannel. For SSL support use com.mongodb.connection.netty.NettyStreamFactoryFactory
        at com.mongodb.connection.AsynchronousSocketChannelStreamFactory.<init>(AsynchronousSocketChannelStreamFactory.java:58)
        at com.mongodb.connection.AsynchronousSocketChannelStreamFactory.<init>(AsynchronousSocketChannelStreamFactory.java:43)
        at com.mongodb.async.client.MongoClients.getStreamFactory(MongoClients.java:226)
        at com.mongodb.async.client.MongoClients.create(MongoClients.java:173)
        at com.mongodb.async.client.MongoClients.create(MongoClients.java:115)
        at cn.playscala.mongo.MongoClient$.apply(MongoClient.scala:123)
        at cn.playscala.mongo.MongoClient$.apply(MongoClient.scala:99)
        at cn.playscala.mongo.MongoClient$.apply(MongoClient.scala:66)
        at cn.playscala.mongo.Mongo.<init>(Mongo.scala:78)
        at GreetingModule.mongo(GreetingModule.scala:12)

```

**Comment by joymufeng** [comment]
Thanks for your feedback,  I will fix it later.

**Comment by joymufeng** [comment]
@Jeremy-Laier  Hi Jeremy，you can manually add the netty dependency for a temporary solution. For example:
```
libraryDependencies += "io.netty" % "netty-all" % "4.1.48.Final"
```

**Comment by joymufeng** [comment]
For ssl support, you should use the following connection string:
```
mongodb.uri="mongodb://sub.domain.com:27017/dbname?ssl=true"
```
And add netty dependency manually:
```
libraryDependencies += "io.netty" % "netty-all" % "4.1.17.Final"
```
